# permissions for end users to edit deployobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: deployobject-editor-role
rules:
- apiGroups:
  - app.my.domain
  resources:
  - deployobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.my.domain
  resources:
  - deployobjects/status
  verbs:
  - get
