# permissions for end users to view zookeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: zookeepercluster-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - zookeeperclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - zookeeperclusters/status
  verbs:
  - get
