apiVersion: app.my.domain/v1
kind: DeployObject
metadata:
  labels:
    app.kubernetes.io/name: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: deployobject-sample
spec:
  # TODO(user): Add fields here
